<?php
/**
 * Implements hook_user_login().
 */
function login_history_user_login(&$edit, $account) {
  db_insert('login_history')
    ->fields( array(
        'uid' => $account -> uid,
        'login' => $account -> name,
        'logintime' => REQUEST_TIME,
      )
    )
    ->execute();
}

/**
 * Implements hook_menu(). 
 */
function login_history_menu() {
  $items['login-history'] = array(
    'title' => 'Login history',
    'page callback' => 'login_history_page',
    'access callback' => TRUE,
    'access arguments' => array('administer site configuration'),
    'type' => MENU_CALLBACK,
  );
  $items['login-count'] = array(
    'title' => 'Login count',
    'page callback' => 'login_count_page',
    'access callback' => TRUE,
    'access arguments' => array('administer site configuration'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Select function.
 */
function login_history_select() {
  $query = db_select('login_history', 'l')
    ->fields('l', array('uid', 'login', 'logintime'))
    ->orderBy('logintime', 'desc')
    ->execute() 
    ->fetchAll();
  return $query;
}

/**
 * Table function.
 */
function login_history_table($header, $rows) {
  $attributes = array(
    'header' => $header,
    'rows' => $rows,
  );
  $output = theme('table', $attributes); 
  return $output;
}

/**
 * Build history page.
 */
function login_history_page() {
  $query = login_history_select();
  $header = array(
    array(
      'data' => t('Uid')
    ),
    array(
      'data' => t('Username')
    ),
    array(
      'data' => t('Time')
    ),
  );
  $rows = array();
  foreach ($query as $record) {
    $rows[] = array(
      array(
        'data' => $record->uid
      ),
      array(
        'data' => $record->login
      ),
      array(
        'data' => format_date($record->logintime, 'long')
      ),
    );
  }
  return login_history_table($header, $rows);
}

/**
 * Build count page.
 */
function login_count_page() {
  $query = login_history_select();
  $count = array();
  foreach ($query as $record) {
    if (!isset($count[$record->uid])) {
      $count[$record->uid] = array();
      $count[$record->uid]['count'] = 0;
    }
    $count[$record->uid]['login'] = $record->login;
    $count[$record->uid]['count'] += 1;
  }
  $header = array(
    array(
      'data' => t('Username')
    ),
    array(
      'data' => t('Logins count')
    ),
  );
  $rows = array();
  foreach ($count as $record) {
    $rows[] = array(
      array(
        'data' => $record['login']
      ),
      array(
        'data' => $record['count']
      ),
    );
  }
  return login_history_table($header, $rows);
}